# Generated by Django 2.2.1 on 2019-05-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190504_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='listId',
        ),
    ]
