# Generated by Django 2.2.1 on 2019-05-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_todoitem_listid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoItem'),
        ),
    ]
