# Generated by Django 2.2.1 on 2019-05-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190505_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todoItem'),
        ),
    ]
