# Generated by Django 2.2.1 on 2019-05-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoItem'),
        ),
    ]
