# Generated by Django 2.2.1 on 2019-05-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190504_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='todo.todoItem'),
        ),
    ]
