# Generated by Django 2.2.1 on 2019-05-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todoitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('listId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='listId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
