# Generated by Django 2.2.1 on 2019-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190505_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
